## Variables required
##
## sonarqubeServiceConnection Name of the service endpoint

parameters:
  - name: configFile
    displayName: Path of SonarQube config file
    type: string
    default: ./sonar-project.properties

steps:
  - script: echo "##vso[task.setvariable variable=version;isoutput=true]$(git rev-parse --short HEAD)"
    name: setVersion
    condition: ne(variables['sonarProjectKey'], '')

  - task: SonarQubePrepare@6
    inputs:
      SonarQube: $(sonarqubeServiceConnection)
      scannerMode: CLI
      configMode: file
      configFile: ${{ parameters.configFile }}
      extraProperties: |
        sonar.projectKey=$(sonarProjectKey)
        sonar.projectVersion=$(setVersion.version)
    condition: ne(variables['sonarProjectKey'], '')

  - task: SonarQubeAnalyze@6
    condition: ne(variables['sonarProjectKey'], '')

  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'
    condition: ne(variables['sonarProjectKey'], '')
